.TH "/home/travis/build/yogeshg/clayer/test/comparisons/boost.cpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/comparisons/boost.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <boost/date_time/posix_time/posix_time_types\&.hpp>\fP
.br
\fC#include <boost/log/trivial\&.hpp>\fP
.br
\fC#include <boost/log/expressions\&.hpp>\fP
.br
\fC#include <boost/log/sources/severity_logger\&.hpp>\fP
.br
\fC#include <boost/log/sources/record_ostream\&.hpp>\fP
.br
\fC#include <boost/log/utility/setup/file\&.hpp>\fP
.br
\fC#include <boost/log/utility/setup/common_attributes\&.hpp>\fP
.br
\fC#include <boost/log/support/date_time\&.hpp>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBworker\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int, char *[])"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBiterations\fP = 1000*50"
.br
.ti -1c
.RI "const int \fBthread_count\fP = 1"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (int, char *[])"
.SS "void \fBworker\fP ()"
.SH "Variable Documentation"
.PP 
.SS "const int \fBiterations\fP = 1000*50"
.SS "const int \fBthread_count\fP = 1"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
