.TH "C" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBC\fP (int a, int b)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBx\fP"
.br
.ti -1c
.RI "int \fBy\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "C::C (inta, intb)\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "int C::x"

.SS "int C::y"


.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
