.TH "case_insensitive_equals" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
case_insensitive_equals \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_http\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator()\fP (const std::string &key1, const std::string &key2) const "
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "bool case_insensitive_equals::operator() (const std::string &key1, const std::string &key2) const\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
