.TH "/home/travis/build/yogeshg/clayer/test/server/client_http.hpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/server/client_http.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <boost/utility/string_ref\&.hpp>\fP
.br
\fC#include <boost/algorithm/string/predicate\&.hpp>\fP
.br
\fC#include <boost/functional/hash\&.hpp>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <map>\fP
.br
\fC#include <random>\fP
.br
\fC#include <mutex>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBcase_insensitive_equals\fP"
.br
.ti -1c
.RI "class \fBcase_insensitive_hash\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ClientBase< socket_type >\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ClientBase< socket_type >::Response\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ClientBase< socket_type >::Config\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::Client< socket_type >\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::Client< HTTP >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSimpleWeb\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBCASE_INSENSITIVE_EQUALS_AND_HASH\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef 
.br
boost::asio::ip::tcp::socket \fBSimpleWeb::HTTP\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBCASE_INSENSITIVE_EQUALS_AND_HASH\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
