.TH "/home/travis/build/yogeshg/clayer/test/comparisons/glog.cpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/comparisons/glog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <thread>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <utility>\fP
.br
\fC#include <glog/logging\&.h>\fP
.br
\fC#include 'stdlib\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBworker\fP ()"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "const int \fBiterations\fP = 1000"
.br
.ti -1c
.RI "const int \fBthread_count\fP = 50"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (intargc, char **argv)"
.SS "void \fBworker\fP ()"
.SH "Variable Documentation"
.PP 
.SS "const int \fBiterations\fP = 1000"
.SS "const int \fBthread_count\fP = 50"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
