.TH "/home/travis/build/yogeshg/clayer/test/server/http_examples.cpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/server/http_examples.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'server_http\&.hpp'\fP
.br
\fC#include 'client_http\&.hpp'\fP
.br
\fC#include 'logconfig\&.h'\fP
.br
\fC#include 'logger\&.h'\fP
.br
\fC#include <boost/property_tree/ptree\&.hpp>\fP
.br
\fC#include <boost/property_tree/json_parser\&.hpp>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include <csignal>\fP
.br

.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBBOOST_SPIRIT_THREADSAFE\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSimpleWeb::Server\fP
.br
< \fBSimpleWeb::HTTP\fP > \fBHttpServer\fP"
.br
.ti -1c
.RI "typedef \fBSimpleWeb::Client\fP
.br
< \fBSimpleWeb::HTTP\fP > \fBHttpClient\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdefault_resource_send\fP (const \fBHttpServer\fP &server, const shared_ptr< HttpServer::Response > &response, const shared_ptr< ifstream > &ifs)"
.br
.ti -1c
.RI "void \fBsig_handler\fP (int signum)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Macro Definition Documentation"
.PP 
.SS "#define BOOST_SPIRIT_THREADSAFE"

.SH "Typedef Documentation"
.PP 
.SS "typedef \fBSimpleWeb::Client\fP<\fBSimpleWeb::HTTP\fP> \fBHttpClient\fP"

.SS "typedef \fBSimpleWeb::Server\fP<\fBSimpleWeb::HTTP\fP> \fBHttpServer\fP"

.SH "Function Documentation"
.PP 
.SS "void default_resource_send (const \fBHttpServer\fP &server, const shared_ptr< HttpServer::Response > &response, const shared_ptr< ifstream > &ifs)"

.SS "int main ()"

.SS "void sig_handler (intsignum)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
