.TH "/home/travis/build/yogeshg/clayer/test/server/https_examples.cpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/server/https_examples.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'server_https\&.hpp'\fP
.br
\fC#include 'client_https\&.hpp'\fP
.br
\fC#include <boost/property_tree/ptree\&.hpp>\fP
.br
\fC#include <boost/property_tree/json_parser\&.hpp>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <boost/filesystem\&.hpp>\fP
.br
\fC#include <vector>\fP
.br
\fC#include <algorithm>\fP
.br
\fC#include 'crypto\&.hpp'\fP
.br

.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBBOOST_SPIRIT_THREADSAFE\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef \fBSimpleWeb::Server\fP
.br
< \fBSimpleWeb::HTTPS\fP > \fBHttpsServer\fP"
.br
.ti -1c
.RI "typedef \fBSimpleWeb::Client\fP
.br
< \fBSimpleWeb::HTTPS\fP > \fBHttpsClient\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBdefault_resource_send\fP (const \fBHttpsServer\fP &server, const shared_ptr< HttpsServer::Response > &response, const shared_ptr< ifstream > &ifs)"
.br
.ti -1c
.RI "int \fBmain\fP ()"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBBOOST_SPIRIT_THREADSAFE\fP"
.SH "Typedef Documentation"
.PP 
.SS "typedef \fBSimpleWeb::Client\fP<\fBSimpleWeb::HTTPS\fP> \fBHttpsClient\fP"
.SS "typedef \fBSimpleWeb::Server\fP<\fBSimpleWeb::HTTPS\fP> \fBHttpsServer\fP"
.SH "Function Documentation"
.PP 
.SS "void \fBdefault_resource_send\fP (const \fBHttpsServer\fP &server, const shared_ptr< HttpsServer::Response > &response, const shared_ptr< ifstream > &ifs)"
.SS "int \fBmain\fP ()"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
