.TH "md__home_travis_build_yogeshg_clayer__r_e_a_d_m_e" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_travis_build_yogeshg_clayer__r_e_a_d_m_e \- Clayer 
Logging and analysis facility in C++ using compile time template meta programming\&.
.PP
\fC![Build Status](https://travis-ci\&.org/yogeshg/clayer\&.svg?branch=master)\fP
.PP
.SS "Simple Usage"
.PP
Include the following headers in your project that needs logging\&.
.PP
```cpp #include 'logconfig\&.h' #include 'logger\&.h' ```
.PP
Clayer uses the standard C++ syntax to stream logging messages to the logger\&. The following line shows a sample usage of the logger\&. It prints the log message 'Start program, begin logging' to \fCstd::clog\fP, with logging level \fCDEBUG\fP
.PP
```cpp \fBLOG(DEBUG)\fP << 'Start program, begin logging'; ```
.PP
To compile your program loaded with Clayer, issue the following command\&. Remember to put Clayer header files in the same directory
.PP
\fCg++ --std=c++1z -fconcepts -lpthread your_program\&.cpp\fP
.PP
.SS "Further Information"
.PP
Library design report, tutorial and documentation can be found in [Project Wiki]\&.
.PP
.SS "Authors"
.PP
Yogesh Garg, Steven Shao, Andy Xu 
