.TH "md__home_travis_build_yogeshg_clayer_docs_old_notes_20170421" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_travis_build_yogeshg_clayer_docs_old_notes_20170421 \- Talk with Jonathan 

.IP "\(bu" 2
We should look to add colors
.IP "  \(bu" 4
it can help us add more template tricks
.IP "  \(bu" 4
also use concepts like printable
.PP

.IP "\(bu" 2
enable functions (?)
.IP "\(bu" 2
use std::integer_sequence - compile time
.IP "\(bu" 2
Good idea to look through http://boost-spirit.com/home/ 
.PP

