.TH "md__home_travis_build_yogeshg_clayer_docs__r_e_a_d_m_e" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_travis_build_yogeshg_clayer_docs__r_e_a_d_m_e \- README 
Documentation is in javadoc format and in the logging code (see e\&.g\&. \fBlogger\&.h\fP, \fBlogconfig\&.h\fP)\&. Doxygen wouldn't play nice given our unorthodox library structure\&. 
