.TH "/home/travis/build/yogeshg/clayer/docs/old/notes_20170421.md" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/docs/old/notes_20170421.md \- 
.SH SYNOPSIS
.br
.PP
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
