.TH "ServerTest" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ServerTest \- 
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBSimpleWeb::ServerBase< HTTP >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBServerTest\fP ()"
.br
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.ti -1c
.RI "void \fBparse_request_test\fP ()"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBServerTest::ServerTest\fP ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void \fBServerTest::accept\fP ()\fC [inline, virtual]\fP"
.PP
Implements \fBSimpleWeb::ServerBase< HTTP >\fP\&.
.SS "void \fBServerTest::parse_request_test\fP ()\fC [inline]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
