.TH "/home/travis/build/yogeshg/clayer/test/server/server_http.hpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/server/server_http.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <boost/asio\&.hpp>\fP
.br
\fC#include <boost/algorithm/string/predicate\&.hpp>\fP
.br
\fC#include <boost/functional/hash\&.hpp>\fP
.br
\fC#include <map>\fP
.br
\fC#include <unordered_map>\fP
.br
\fC#include <thread>\fP
.br
\fC#include <functional>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include <regex>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleWeb::ServerBase< socket_type >\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ServerBase< socket_type >::Response\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ServerBase< socket_type >::Content\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ServerBase< socket_type >::Request\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ServerBase< socket_type >::Config\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::ServerBase< socket_type >::regex_orderable\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::Server< socket_type >\fP"
.br
.ti -1c
.RI "class \fBSimpleWeb::Server< HTTP >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBSimpleWeb\fP"
.br
.in -1c
.SS "Defines"

.in +1c
.ti -1c
.RI "#define \fBREGEX_NS\fP   \fBstd\fP"
.br
.in -1c
.SH "Define Documentation"
.PP 
.SS "#define \fBREGEX_NS\fP   \fBstd\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
