.TH "/home/travis/build/yogeshg/clayer/test/server/server_https.hpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/test/server/server_https.hpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'server_http\&.hpp'\fP
.br
\fC#include <boost/asio/ssl\&.hpp>\fP
.br
\fC#include <openssl/ssl\&.h>\fP
.br
\fC#include <algorithm>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSimpleWeb::Server< HTTPS >\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "\fBSimpleWeb\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
