.TH "SimpleWeb::Client< HTTPS >" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::Client< HTTPS > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_https\&.hpp>\fP
.PP
Inherits \fBSimpleWeb::ClientBase< HTTPS >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (const std::string &server_port_path, bool verify_certificate=true, const std::string &cert_file=std::string(), const std::string &private_key_file=std::string(), const std::string &verify_file=std::string())"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBconnect\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "boost::asio::ssl::context \fBcontext\fP"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSimpleWeb::Client\fP< \fBHTTPS\fP >::\fBClient\fP (const std::string &server_port_path, boolverify_certificate = \fCtrue\fP, const std::string &cert_file = \fCstd::string()\fP, const std::string &private_key_file = \fCstd::string()\fP, const std::string &verify_file = \fCstd::string()\fP)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void \fBSimpleWeb::Client\fP< \fBHTTPS\fP >::connect ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBSimpleWeb::ClientBase< HTTPS >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "boost::asio::ssl::context \fBSimpleWeb::Client\fP< \fBHTTPS\fP >::context\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
