.TH "SimpleWeb::Client< HTTP >" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::Client< HTTP > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_http\&.hpp>\fP
.PP
Inherits \fBSimpleWeb::ClientBase< HTTP >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBClient\fP (const std::string &server_port_path)"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBconnect\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBSimpleWeb::Client\fP< \fBHTTP\fP >::\fBClient\fP (const std::string &server_port_path)\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void \fBSimpleWeb::Client\fP< \fBHTTP\fP >::connect ()\fC [inline]\fP, \fC [protected]\fP, \fC [virtual]\fP"

.PP
Implements \fBSimpleWeb::ClientBase< HTTP >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
