.TH "SimpleWeb::Crypto::Base64" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::Crypto::Base64 \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crypto\&.hpp>\fP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBencode\fP (const std::string &ascii)"
.br
.ti -1c
.RI "static std::string \fBdecode\fP (const std::string &base64)"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static std::string \fBSimpleWeb::Crypto::Base64::decode\fP (const std::string &base64)\fC [inline, static]\fP"
.SS "static std::string \fBSimpleWeb::Crypto::Base64::encode\fP (const std::string &ascii)\fC [inline, static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
