.TH "SimpleWeb::Client< socket_type >" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::Client< socket_type > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_http\&.hpp>\fP
.PP
Inherits \fBSimpleWeb::ClientBase< socket_type >\fP\&.
.SS "Additional Inherited Members"


.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
