.TH "SimpleWeb::Crypto" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::Crypto \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <crypto\&.hpp>\fP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBase64\fP"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static std::string \fBto_hex_string\fP (const std::string &input)"
.br
.RI "\fIReturn hex string from bytes in input string\&. \fP"
.ti -1c
.RI "static std::string \fBmd5\fP (const std::string &input, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBmd5\fP (std::istream &stream, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBsha1\fP (const std::string &input, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBsha1\fP (std::istream &stream, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBsha256\fP (const std::string &input, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBsha256\fP (std::istream &stream, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBsha512\fP (const std::string &input, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBsha512\fP (std::istream &stream, size_t \fBiterations\fP=1)"
.br
.ti -1c
.RI "static std::string \fBpbkdf2\fP (const std::string &password, const std::string &salt, int \fBiterations\fP, int key_size)"
.br
.RI "\fIkey_size is number of bytes of the returned key\&. \fP"
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "static std::string SimpleWeb::Crypto::md5 (const std::string &input, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::md5 (std::istream &stream, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::pbkdf2 (const std::string &password, const std::string &salt, intiterations, intkey_size)\fC [inline]\fP, \fC [static]\fP"

.PP
key_size is number of bytes of the returned key\&. 
.SS "static std::string SimpleWeb::Crypto::sha1 (const std::string &input, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::sha1 (std::istream &stream, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::sha256 (const std::string &input, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::sha256 (std::istream &stream, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::sha512 (const std::string &input, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::sha512 (std::istream &stream, size_titerations = \fC1\fP)\fC [inline]\fP, \fC [static]\fP"

.SS "static std::string SimpleWeb::Crypto::to_hex_string (const std::string &input)\fC [inline]\fP, \fC [static]\fP"

.PP
Return hex string from bytes in input string\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
