.TH "SimpleWeb" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBClientBase\fP"
.br
.ti -1c
.RI "class \fBClient\fP"
.br
.ti -1c
.RI "class \fBClient< HTTP >\fP"
.br
.ti -1c
.RI "class \fBClient< HTTPS >\fP"
.br
.ti -1c
.RI "class \fBCrypto\fP"
.br
.ti -1c
.RI "class \fBServerBase\fP"
.br
.ti -1c
.RI "class \fBServer\fP"
.br
.ti -1c
.RI "class \fBServer< HTTP >\fP"
.br
.ti -1c
.RI "class \fBServer< HTTPS >\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef 
.br
boost::asio::ip::tcp::socket \fBHTTP\fP"
.br
.ti -1c
.RI "typedef 
.br
boost::asio::ssl::stream
.br
< boost::asio::ip::tcp::socket > \fBHTTPS\fP"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef boost::asio::ip::tcp::socket \fBSimpleWeb::HTTP\fP"
.SS "typedef boost::asio::ssl::stream< boost::asio::ip::tcp::socket > \fBSimpleWeb::HTTPS\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
