.TH "SimpleWeb::ServerBase< socket_type >::Content" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::ServerBase< socket_type >::Content \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server_http\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.ti -1c
.RI "std::string \fBstring\fP ()"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBServerBase< socket_type >\fP"
.br
.in -1c

.SS "template<class socket_type> class SimpleWeb::ServerBase< socket_type >::Content"

.SH "Member Function Documentation"
.PP 
.SS "template<class socket_type> size_t \fBSimpleWeb::ServerBase\fP< socket_type >::\fBContent::size\fP ()\fC [inline]\fP"
.SS "template<class socket_type> std::string \fBSimpleWeb::ServerBase\fP< socket_type >::\fBContent::string\fP ()\fC [inline]\fP"
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class socket_type> friend class \fBServerBase\fP< socket_type >\fC [friend]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
