.TH "SimpleWeb::Server< HTTP >" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::Server< HTTP > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server_http\&.hpp>\fP
.PP
Inherits \fBSimpleWeb::ServerBase< HTTP >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "DEPRECATED \fBServer\fP (unsigned short port, size_t thread_pool_size=1, long timeout_request=5, long timeout_content=300)"
.br
.ti -1c
.RI "\fBServer\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "void \fBaccept\fP ()"
.br
.in -1c

.SS "template<> class SimpleWeb::Server< HTTP >"

.SH "Constructor & Destructor Documentation"
.PP 
.SS "DEPRECATED \fBSimpleWeb::Server\fP< \fBHTTP\fP >::\fBServer\fP (unsigned shortport, size_tthread_pool_size = \fC1\fP, longtimeout_request = \fC5\fP, longtimeout_content = \fC300\fP)\fC [inline]\fP"
.SS "\fBSimpleWeb::Server\fP< \fBHTTP\fP >::\fBServer\fP ()\fC [inline]\fP"
.SH "Member Function Documentation"
.PP 
.SS "void \fBSimpleWeb::Server\fP< \fBHTTP\fP >::\fBaccept\fP ()\fC [inline, protected, virtual]\fP"
.PP
Implements \fBSimpleWeb::ServerBase< HTTP >\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
