.TH "SimpleWeb::ClientBase< socket_type >::Config" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::ClientBase< socket_type >::Config \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <client_http\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "size_t \fBtimeout\fP = 0"
.br
.RI "\fISet timeout on requests in seconds\&. Default value: 0 (no timeout)\&. \fP"
.ti -1c
.RI "size_t \fBtimeout_connect\fP = 0"
.br
.RI "\fISet connect timeout in seconds\&. Default value: 0 (\fBConfig::timeout\fP is then used instead)\&. \fP"
.ti -1c
.RI "std::string \fBproxy_server\fP"
.br
.RI "\fISet proxy server (server:port) \fP"
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBClientBase< socket_type >\fP"
.br
.in -1c

.SS "template<class socket_type> class SimpleWeb::ClientBase< socket_type >::Config"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class socket_type> friend class \fBClientBase\fP< socket_type >\fC [friend]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class socket_type> std::string \fBSimpleWeb::ClientBase\fP< socket_type >::\fBConfig::proxy_server\fP"
.PP
Set proxy server (server:port) 
.SS "template<class socket_type> size_t \fBSimpleWeb::ClientBase\fP< socket_type >::\fBConfig::timeout\fP = 0"
.PP
Set timeout on requests in seconds\&. Default value: 0 (no timeout)\&. 
.SS "template<class socket_type> size_t \fBSimpleWeb::ClientBase\fP< socket_type >::\fBConfig::timeout_connect\fP = 0"
.PP
Set connect timeout in seconds\&. Default value: 0 (\fBConfig::timeout\fP is then used instead)\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
