.TH "SimpleWeb::ServerBase< socket_type >::Response" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::ServerBase< socket_type >::Response \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server_http\&.hpp>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "size_t \fBsize\fP ()"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBclose_connection_after_response\fP = false"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBServerBase< socket_type >\fP"
.br
.in -1c

.SS "template<class socket_type> class SimpleWeb::ServerBase< socket_type >::Response"

.SH "Member Function Documentation"
.PP 
.SS "template<class socket_type> size_t \fBSimpleWeb::ServerBase\fP< socket_type >::\fBResponse::size\fP ()\fC [inline]\fP"
.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class socket_type> friend class \fBServerBase\fP< socket_type >\fC [friend]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class socket_type> bool \fBSimpleWeb::ServerBase\fP< socket_type >::\fBResponse::close_connection_after_response\fP = false"If true, force server to close the connection after the response have been sent\&.
.PP
This is useful when implementing a HTTP/1\&.0-server sending content without specifying the content length\&. 

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
