.TH "SimpleWeb::ServerBase< socket_type >::Request" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SimpleWeb::ServerBase< socket_type >::Request \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <server_http\&.hpp>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBmethod\fP"
.br
.ti -1c
.RI "std::string \fBpath\fP"
.br
.ti -1c
.RI "std::string \fBhttp_version\fP"
.br
.ti -1c
.RI "\fBContent\fP \fBcontent\fP"
.br
.ti -1c
.RI "std::unordered_multimap
.br
< std::string, std::string, 
.br
\fBcase_insensitive_hash\fP, 
.br
\fBcase_insensitive_equals\fP > \fBheader\fP"
.br
.ti -1c
.RI "REGEX_NS::smatch \fBpath_match\fP"
.br
.ti -1c
.RI "std::string \fBremote_endpoint_address\fP"
.br
.ti -1c
.RI "unsigned short \fBremote_endpoint_port\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBServerBase< socket_type >\fP"
.br
.ti -1c
.RI "class \fBServer< socket_type >\fP"
.br
.in -1c

.SS "template<class socket_type> class SimpleWeb::ServerBase< socket_type >::Request"

.SH "Friends And Related Function Documentation"
.PP 
.SS "template<class socket_type> friend class \fBServer\fP< socket_type >\fC [friend]\fP"
.SS "template<class socket_type> friend class \fBServerBase\fP< socket_type >\fC [friend]\fP"
.SH "Member Data Documentation"
.PP 
.SS "template<class socket_type> \fBContent\fP \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::content\fP"
.SS "template<class socket_type> std::unordered_multimap<std::string, std::string, \fBcase_insensitive_hash\fP, \fBcase_insensitive_equals\fP> \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::header\fP"
.SS "template<class socket_type> std::string \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::http_version\fP"
.SS "template<class socket_type> std::string \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::method\fP"
.SS "template<class socket_type> std::string \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::path\fP"
.SS "template<class socket_type> REGEX_NS::smatch \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::path_match\fP"
.SS "template<class socket_type> std::string \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::remote_endpoint_address\fP"
.SS "template<class socket_type> unsigned short \fBSimpleWeb::ServerBase\fP< socket_type >::\fBRequest::remote_endpoint_port\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
