.TH "/home/travis/build/yogeshg/clayer/samples/t3.h" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/samples/t3.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBprint\fP ()"
.br
.ti -1c
.RI "template<Streamable T, typename\&.\&.\&. Targs> void \fBprint\fP (T o, Targs\&.\&.\&.tail)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "concept bool \fBStreamable\fP"
.br
.ti -1c
.RI "concept bool \fBStringRef\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void \fBprint\fP ()"
.SS "template<Streamable T, typename\&.\&.\&. Targs> void \fBprint\fP (To, Targs\&.\&.\&.tail)"
.SH "Variable Documentation"
.PP 
.SS "concept bool \fBStreamable\fP"\fBInitial value:\fP
.PP
.nf
 requires(T o, std::ostream& s) {
    {s << o} -> std::ostream&;
}
.fi
.SS "concept bool \fBStringRef\fP"\fBInitial value:\fP
.PP
.nf
 requires(T o) {
    {*o} -> std::string;
}
.fi
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
