.TH "/home/travis/build/yogeshg/clayer/samples/t4.cpp" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/samples/t4.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <vector>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <sstream>\fP
.br
\fC#include 't3\&.h'\fP
.br

.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBPoperties\fP { \fBDATE\fP, \fBLINE\fP, \fBFUNC\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "template<int N> void \fBread_prop\fP (std::istringstream s)"
.br
.ti -1c
.RI "template<> void \fBread_prop< DATE >\fP (std::istringstream is)"
.br
.ti -1c
.RI "template<> void \fBread_prop< FUNC >\fP (std::istringstream is)"
.br
.ti -1c
.RI "template<> void \fBread_prop< LINE >\fP (std::istringstream is)"
.br
.ti -1c
.RI "template<StringRef P> void \fBread_props\fP (P)"
.br
.ti -1c
.RI "template<StringRef P, int head, int\&.\&.\&. I> void \fBread_props\fP (P p)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "std::string \fBdate\fP"
.br
.ti -1c
.RI "std::string \fBfunc\fP"
.br
.ti -1c
.RI "int \fBline\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBPoperties\fP"
.PP
\fBEnumerator: \fP
.in +1c
.TP
\fB\fIDATE \fP\fP
.TP
\fB\fILINE \fP\fP
.TP
\fB\fIFUNC \fP\fP

.SH "Function Documentation"
.PP 
.SS "template<int N> void \fBread_prop\fP (std::istringstreams)"
.SS "template<> void \fBread_prop\fP< \fBDATE\fP > (std::istringstreamis)"
.SS "template<> void \fBread_prop\fP< \fBFUNC\fP > (std::istringstreamis)"
.SS "template<> void \fBread_prop\fP< \fBLINE\fP > (std::istringstreamis)"
.SS "template<StringRef P> void \fBread_props\fP (P)"
.SS "template<StringRef P, int head, int\&.\&.\&. I> void \fBread_props\fP (Pp)"
.SH "Variable Documentation"
.PP 
.SS "std::string \fBdate\fP"
.SS "std::string \fBfunc\fP"
.SS "int \fBline\fP"
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
