.TH "/home/travis/build/yogeshg/clayer/include/util.h" 3 "Sat Apr 29 2017" "Clayer" \" -*- nroff -*-
.ad l
.nh
.SH NAME
/home/travis/build/yogeshg/clayer/include/util.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <iostream>\fP
.br
\fC#include <string>\fP
.br
\fC#include <tuple>\fP
.br
\fC#include <type_traits>\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBclayer\fP"
.br
.ti -1c
.RI "namespace \fBclayer::util\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Clayer from the source code\&.
